import { SanityLive } from "@/sanity/live";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { sanityFetch } from "@/sanity/live";
import { SITE_SETTINGS_QUERY } from "@/sanity/queries";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@repo/ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { data: settings } = await sanityFetch({ query: SITE_SETTINGS_QUERY });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header settings={settings} />
        {children}
        <SanityLive />
        <Footer />
      </body>
    </html>
  );
}
