import { SanityLive } from "@/sanity/live";
import { Header } from "@repo/modules/header";
import { Footer } from "@repo/modules/footer";
import { sanityFetch } from "@/sanity/live";
import { SITE_SETTINGS_QUERY } from "@/sanity/queries";
import { urlFor } from "@/sanity/image";
import "@repo/ui/styles.css";
import "@repo/modules/styles.css";
import "./globals.css";
import { notFound } from "next/navigation";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { data: siteSettings } = await sanityFetch({
    query: SITE_SETTINGS_QUERY,
  });

  if (!siteSettings) {
    return notFound();
  }

  // Map the raw site settings document to the HeaderModule shape expected by <Header />.
  const headerData = {
    _type: "header",
    siteTitle: siteSettings.siteTitle ?? undefined,
    logo: siteSettings.logo
      ? urlFor(siteSettings.logo).width(128).height(128).url()
      : undefined,
    headerMenu:
      siteSettings.headerMenu?.items?.filter(Boolean).map((item) => ({
        label: item?.label || "",
        href: item?.target?.slug || "",
      })) || [],
  };

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="mx-auto max-w-[var(--layout-max)] px-4 md:px-8">
          <Header data={headerData} />
          {children}
          <SanityLive />
          <Footer />
        </div>
      </body>
    </html>
  );
}
